FROM ubuntu/nginx

EXPOSE 80

ENV NODE_ENV=production

RUN apt update && apt upgrade -y

WORKDIR /app

RUN apt install cargo curl -y

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

RUN apt install nodejs -y

RUN npm i -location=global npm@latest

RUN npm install --location=global yarn

RUN npm install --location=global pm2

COPY . /app

RUN yarn install

RUN yarn build

COPY nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT ["bash", "start.sh"]
