version: "3.8"

services:
  db:
    restart: always
    image: "postgres:14.1-alpine"
    volumes:
       - ./postgres-data:/data/postgres
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: superseekers
    ports:
      - 5050:5050
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    volumes:
      # Note, not all possibly editable files have been added
      # If your changes are not hot-reloaded, it's probably
      # because it's not included in the list below
      - ./frontend/pages:/app/pages
      - ./frontend/components:/app/components
      - ./frontend/public:/app/public
      - ./frontend/styles:/app/styles
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 80:80

  backend:
    build: ./backend
    depends_on:
      - db