version: "3.8"

services:
  postgres:
    restart: always
    image: "postgres:14.1-alpine"
    volumes:
       - ./postgres-data:/data/postgres
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres

  pgadmin:
    # Nota bene check pgadmin.servers.json
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: superseekers
    ports:
      - "5050:80"
    depends_on:
      - postgres