version: "3.8"

services:
  db:
    restart: always
    image: "postgres:14.1-alpine"
    volumes:
       - ./postgres-data:/data/postgres
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: superseekers
    ports:
      - 5050:5050
    depends_on:
      - db

  backend:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080