INSERT INTO Event
    (id,
    image_URL,
    event_name,
    event_description,
    start_time,
    min_age,
    max_age,
    cancelled,
    organizer_id,
    event_address,
    zip_code,
    price,
    max_adults_per_family,
    max_children_per_family,
    places_available,
    begin_date,
    end_date,
    email_contact)
VALUES
    (  1,
        'xxx',
		'Sea Life',
        'Discover over 3.000 creatures in more than 33 displays.',
        '9:00',
        3,
        14,
        false,
        2,
        'Sea Life, Moosach',
        '80335',
        16.00,
        2,
        2,
        10,
        '2022-06-03',
        '2022-06-04',
        'info@kunstlabor.org'
    );