kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: balancedpd-storageclass
  namespace: development
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-balanced
  replication-type: none
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv
  namespace: development
spec:
  storageClassName: balancedpd-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
