name: Backend Build

on:
  # run it on push to the staging repository branch
  push:
    branches: 
      - main
      - development
    paths: 
      - 'backend/**'

jobs:
  build-backend:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      context: ./backend
      image-name: backend
      deployment-name: backend-deployment
      username: ${{ github.actor }}
      environment: development
      cluster-name: seakers
      zone: europe-west2
      project: batch16-projects
      dockerfile: Dockerfile
      repository: batch16--seakers
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      REACT_SPRING_TEMPLATE_SA: ${{ secrets.REACT_SPRING_TEMPLATE_SA }}